# Generated by Django 4.2.1 on 2023-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamentos_dia', models.IntegerField(default=0)),
                ('agendamentos_semana', models.IntegerField(default=0)),
                ('agendamentos_mes', models.IntegerField(default=0)),
                ('agendamentos_ano', models.IntegerField(default=0)),
                ('cancelamento_dia', models.IntegerField(default=0)),
                ('cancelamento_semana', models.IntegerField(default=0)),
                ('cancelamento_mes', models.IntegerField(default=0)),
                ('cancelamento_ano', models.IntegerField(default=0)),
            ],
        ),
    ]
