# Generated by Django 4.2.1 on 2023-07-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agendamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='centro_esportivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.centroesportivos'),
            preserve_default=False,
        ),
    ]
