# Generated by Django 4.2.3 on 2023-07-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_agendamentos_centro_esportivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo_cliente', models.CharField(max_length=20)),
                ('semana', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terca'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'SEX'), ('SAB', 'Sabado'), ('DOM', 'Domingo')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semana_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_pix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_cartão', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro_esportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.centroesportivos')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoDiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.IntegerField(default=0)),
                ('terca', models.IntegerField(default=0)),
                ('quarta', models.IntegerField(default=0)),
                ('quinta', models.IntegerField(default=0)),
                ('sexta', models.IntegerField(default=0)),
                ('sabado', models.IntegerField(default=0)),
                ('domingo', models.IntegerField(default=0)),
                ('centor_esportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.centroesportivos')),
            ],
        ),
    ]
